### ISSUE TITLE
Reading tfrecord file

### ISSUE THREAD

**Issue by Noemie-B** [smujiang/WSITools#5]
Hi
Is it possible please to have an example of reading the tfrecord file please ? In fact, I'm facing a  lot of issues.

Thanks for your help !

**Comment by smujiang** [comment]
Thanks for asking. The output tfrecord file from this tool is the standard tfrecord. You can find the the way to read tfrecord file by refering this example (https://www.tensorflow.org/tutorials/load_data/tfrecord).
For this repo, you may need to define your own feature map for creating tfrecord file depending on your task. Please refer the examples in: WSITools/wsitools/patch_extraction/feature_maps.

Indeed, many functions of this tool need to be optimized. Feel free to contribute code if you can.

**Comment by smujiang** [comment]
close due to low activation
